# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/as-admin/cxz/learning/neverdb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/as-admin/cxz/learning/neverdb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/as-admin/cxz/learning/neverdb/CMakeFiles /home/as-admin/cxz/learning/neverdb//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/as-admin/cxz/learning/neverdb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_utils

# Build rule for target.
test_utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_utils
.PHONY : test_utils

# fast build rule for target.
test_utils/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/build
.PHONY : test_utils/fast

#=============================================================================
# Target rules for targets named skiplist_test

# Build rule for target.
skiplist_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 skiplist_test
.PHONY : skiplist_test

# fast build rule for target.
skiplist_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skiplist_test.dir/build.make CMakeFiles/skiplist_test.dir/build
.PHONY : skiplist_test/fast

#=============================================================================
# Target rules for targets named memtable_test

# Build rule for target.
memtable_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 memtable_test
.PHONY : memtable_test

# fast build rule for target.
memtable_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memtable_test.dir/build.make CMakeFiles/memtable_test.dir/build
.PHONY : memtable_test/fast

#=============================================================================
# Target rules for targets named block_test

# Build rule for target.
block_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 block_test
.PHONY : block_test

# fast build rule for target.
block_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/block_test.dir/build.make CMakeFiles/block_test.dir/build
.PHONY : block_test/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

test/block_test.o: test/block_test.cc.o
.PHONY : test/block_test.o

# target to build an object file
test/block_test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/block_test.dir/build.make CMakeFiles/block_test.dir/test/block_test.cc.o
.PHONY : test/block_test.cc.o

test/block_test.i: test/block_test.cc.i
.PHONY : test/block_test.i

# target to preprocess a source file
test/block_test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/block_test.dir/build.make CMakeFiles/block_test.dir/test/block_test.cc.i
.PHONY : test/block_test.cc.i

test/block_test.s: test/block_test.cc.s
.PHONY : test/block_test.s

# target to generate assembly for a file
test/block_test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/block_test.dir/build.make CMakeFiles/block_test.dir/test/block_test.cc.s
.PHONY : test/block_test.cc.s

test/memtable_test.o: test/memtable_test.cc.o
.PHONY : test/memtable_test.o

# target to build an object file
test/memtable_test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memtable_test.dir/build.make CMakeFiles/memtable_test.dir/test/memtable_test.cc.o
.PHONY : test/memtable_test.cc.o

test/memtable_test.i: test/memtable_test.cc.i
.PHONY : test/memtable_test.i

# target to preprocess a source file
test/memtable_test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memtable_test.dir/build.make CMakeFiles/memtable_test.dir/test/memtable_test.cc.i
.PHONY : test/memtable_test.cc.i

test/memtable_test.s: test/memtable_test.cc.s
.PHONY : test/memtable_test.s

# target to generate assembly for a file
test/memtable_test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memtable_test.dir/build.make CMakeFiles/memtable_test.dir/test/memtable_test.cc.s
.PHONY : test/memtable_test.cc.s

test/skiplist_test.o: test/skiplist_test.cc.o
.PHONY : test/skiplist_test.o

# target to build an object file
test/skiplist_test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skiplist_test.dir/build.make CMakeFiles/skiplist_test.dir/test/skiplist_test.cc.o
.PHONY : test/skiplist_test.cc.o

test/skiplist_test.i: test/skiplist_test.cc.i
.PHONY : test/skiplist_test.i

# target to preprocess a source file
test/skiplist_test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skiplist_test.dir/build.make CMakeFiles/skiplist_test.dir/test/skiplist_test.cc.i
.PHONY : test/skiplist_test.cc.i

test/skiplist_test.s: test/skiplist_test.cc.s
.PHONY : test/skiplist_test.s

# target to generate assembly for a file
test/skiplist_test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/skiplist_test.dir/build.make CMakeFiles/skiplist_test.dir/test/skiplist_test.cc.s
.PHONY : test/skiplist_test.cc.s

utils/testutils.o: utils/testutils.cc.o
.PHONY : utils/testutils.o

# target to build an object file
utils/testutils.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/utils/testutils.cc.o
.PHONY : utils/testutils.cc.o

utils/testutils.i: utils/testutils.cc.i
.PHONY : utils/testutils.i

# target to preprocess a source file
utils/testutils.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/utils/testutils.cc.i
.PHONY : utils/testutils.cc.i

utils/testutils.s: utils/testutils.cc.s
.PHONY : utils/testutils.s

# target to generate assembly for a file
utils/testutils.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/utils/testutils.cc.s
.PHONY : utils/testutils.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... block_test"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... memtable_test"
	@echo "... skiplist_test"
	@echo "... test_utils"
	@echo "... test/block_test.o"
	@echo "... test/block_test.i"
	@echo "... test/block_test.s"
	@echo "... test/memtable_test.o"
	@echo "... test/memtable_test.i"
	@echo "... test/memtable_test.s"
	@echo "... test/skiplist_test.o"
	@echo "... test/skiplist_test.i"
	@echo "... test/skiplist_test.s"
	@echo "... utils/testutils.o"
	@echo "... utils/testutils.i"
	@echo "... utils/testutils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

